[package]
name = "mandelbrot"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/oovm/mandelbrot.rs"
documentation = "https://docs.rs/sub_projects"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]
num = "0.4.1"
image = { version = "0.24.7", features = [] }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
